### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by syifarahmat** [JicuNull/WhatsJava#2]
I Try you library always error after login success...!
![image](https://user-images.githubusercontent.com/11779955/92111480-91247c00-ee16-11ea-9c71-8c745c34b704.png)

but is oke for send & receive message

**Comment by JicuNull** [comment]
Hey, thanks for trying out the library!

I have just tried it again and I can't reproduce your error. So it would be interesting to know which message should be decoded and causes the error.

You could change the `readNode` method within the `BinaryDecoder` class to find out what the message contains.
Something like this:
```java
// Conversation messages
case BinaryConstants.Tags.BINARY_8:
    byte[] bin8 = readBytes(readByte() & 0xff);
    
    // Insert here
    System.out.println("BIN8: " + new String(bin8));

    base64Decoded = Base64.getEncoder().encodeToString(
    WebMessageInfo.parseFrom(bin8).toByteArray());
							
    break;
```

Be aware that the message may contain personal information before you post it.

For now you may comment out the exception if it should bother you.

Thanks again for helping!

**Comment by syifarahmat** [comment]
***** No personal information here 😄  *****
This is end before error :
![image](https://user-images.githubusercontent.com/11779955/92151004-91d70580-ee4a-11ea-888c-33067ec2a9cf.png)

**Comment by JicuNull** [comment]
Hm, that's strange.

The "message" messages are always encoded in protobuf format, so it's strange that the message is directly readable without artifacts.

Can you tell me if this is a "normal" text message or something else?
I would guess that this is a status message, right?

In fact, I have never tested status messages that contain only text, because for some reason they don't load on my device and I never bothered about it :satisfied:

**Comment by syifarahmat** [comment]
> I would guess that this is a status message, right?
yes this status message.....

Yes.... This bug, after the status message has been more than 24 hours and there are no more, there are no errors

Thanks job 👍
