### ISSUE TITLE
Send Image Message

### ISSUE THREAD

**Issue by isaacmorais** [JicuNull/WhatsJava#5]
Hi ! Do you have some example of how send Image  ?

**Comment by JicuNull** [comment]
Hey,

Sorry, there is no example for sending an image, because this function, like many other things, is not implemented. You could have a look at the Typescript Implementation [Baileys](https://github.com/adiwajshing/Baileys) to see how it works and implement it yourself in Java.

For now I will not work on it.

**Comment by isaacmorais** [comment]
Ok, thanks for the information. I liked your your library and when this functionality is available it will help so much. I will try to check Baileys implementation.
